<a href="https://colab.research.google.com/github/laway/tensorflow/blob/main/00_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework #00

In [15]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

import tensorflow as tf

vector = tf.constant([1,5])
matrix = tf.constant([[1,3],[3,4]])
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[10,11]]])


In [16]:
#Find the shape, rank and size of the tensors you created in 1.
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [17]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [18]:
tensor.shape,tensor.ndim, tf.size(tensor)

(TensorShape([3, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [21]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
tf.random.set_seed(42)
t1 = tf.random.uniform([5,300], 0, 1)
t2 = tf.random.uniform([5,300], 0, 1)

t1,t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [22]:
# Multiply the two tensors you created in 3 using matrix multiplication.
t1*t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
        2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
       [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
        2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
       [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
        1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
       [6.55430436e-01, 5.76979630e-02, 9.58052557e-03, ...,
        6.53199196e-01, 5.08804396e-02, 7.79080987e-01],
       [5.81960231e-02, 1.10622704e-01, 2.62571156e-01, ...,
        6.09022558e-01, 1.02241419e-01, 1.14069067e-01]], dtype=float32)>

In [28]:
# Multiply the two tensors you created in 3 using dot product.
tf.tensordot(t1, tf.transpose(t2), 1), tf.matmul(t1, tf.transpose(t2))

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
        [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
        [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
        [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
        [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
        [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
        [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
        [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
        [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
       dtype=float32)>)

In [29]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(42)

t3 = tf.random.uniform([224, 244, 3], 0, 1)
t3


<tf.Tensor: shape=(224, 244, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.14993274, 0.95743346, 0.0678556 ],
        [0.33755875, 0.2586832 , 0.31682265],
        [0.12932086, 0.6521549 , 0.6951654 ]],

       [[0.26241148, 0.36942792, 0.53326666],
        [0.2040397 , 0.21521878, 0.48851562],
        [0.5410471 , 0.55548096, 0.46440542],
        ...,
        [0.9536427 , 0.66850245, 0.50709856],
        [0.560426  , 0.6647233 , 0.1626333 ],
        [0.56197023, 0.4659928 , 0.8837141 ]],

       [[0.67773116, 0.88375974, 0.7615204 ],
        [0.53757155, 0.5554961 , 0.3356905 ],
        [0.7514802 , 0.10988402, 0.46292984],
        ...,
        [0.28655422, 0.00708723, 0.39797664],
        [0.32293415, 0.68600273, 0.2258904 ],
        [0.3624704 , 0.2741145 , 0.6718725 ]],

       ...,

       [[0.919891  , 0.21909833, 0.23931599],
        [0.37

In [32]:
# Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(t3, 1), tf.reduce_max(t3, 1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[3.08728218e-03, 3.35657597e-03, 3.03745270e-04],
        [2.07266808e-02, 4.31776047e-04, 1.91926956e-04],
        [2.71177292e-03, 7.08723068e-03, 6.09242916e-03],
        [4.06265259e-04, 6.21199608e-03, 1.44493580e-03],
        [1.61790848e-03, 1.41925812e-02, 8.27538967e-03],
        [4.93729115e-03, 1.22084618e-02, 1.14864111e-02],
        [1.54995918e-03, 1.96862221e-03, 8.63945484e-03],
        [4.14669514e-03, 2.41160393e-03, 2.58970261e-03],
        [4.12750244e-03, 4.39548492e-03, 4.06324863e-03],
        [7.61234760e-03, 4.31275368e-03, 5.05447388e-04],
        [4.75323200e-03, 1.07632875e-02, 6.26456738e-03],
        [2.37929821e-03, 1.08909607e-03, 6.28829002e-04],
        [2.86233425e-03, 2.10285187e-04, 2.23445892e-03],
        [5.92350960e-04, 6.08563423e-04, 1.82008743e-03],
        [7.75337219e-03, 4.53341007e-03, 6.29305840e-04],
        [2.28178501e-03, 4.94015217e-03, 1.54292583e-03],
        [2.26211548e-

In [34]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
t4 = tf.random.uniform([1, 224, 224, 3])
t4_squeezed = tf.squeeze(t4)

t4, t4_squeezed

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.7413678 , 0.62854624, 0.01738465],
          [0.3431449 , 0.51063764, 0.3777541 ],
          [0.07321596, 0.02137029, 0.2871771 ],
          ...,
          [0.98953485, 0.45382905, 0.2006687 ],
          [0.6295223 , 0.4937899 , 0.01816809],
          [0.95386636, 0.11542463, 0.85691285]],
 
         [[0.78435016, 0.7826872 , 0.87936425],
          [0.24906898, 0.3207239 , 0.10955775],
          [0.543224  , 0.7151396 , 0.40334642],
          ...,
          [0.2445668 , 0.01746976, 0.9036933 ],
          [0.02975535, 0.592268  , 0.9877522 ],
          [0.36701274, 0.33112562, 0.5638567 ]],
 
         [[0.15829337, 0.7288823 , 0.3366307 ],
          [0.70792687, 0.16910625, 0.9429966 ],
          [0.10120225, 0.5919596 , 0.8687303 ],
          ...,
          [0.28134012, 0.10011208, 0.37038183],
          [0.77874243, 0.05421627, 0.4664607 ],
          [0.2549187 , 0.7968637 , 0.83405185]],
 
         ...,
 
       

In [35]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
t5 = tf.constant([1,4,67,8,23,67,98,12,3,4])
tf.argmax(t5)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [37]:
# One-hot encode the tensor you created in 9.
tf.one_hot(t5, 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>